databases:
  - name: speqq-db
    databaseName: speqq
    region: oregon
    plan: starter

services:
  # Main Speqq Next.js Application
  - type: web
    name: speqq-app
    runtime: node
    repo: https://github.com/jbroxton/prototpe
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: speqq-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # You'll need to set this manually in Render dashboard
      - key: MODEL
        value: gpt-4o-mini
      - key: NODE_ENV
        value: production
      - key: GITHUB_WEBHOOK_SECRET
        generateValue: true
      - key: WEBHOOK_PUBLIC_URL
        value: https://speqq-app.onrender.com
      - key: GITHUB_TOKEN
        sync: false  # You'll need to set this manually in Render dashboard
      - key: JIRA_URL
        value: https://justinmbroxton.atlassian.net
      - key: JIRA_EMAIL
        value: justinmbroxton@gmail.com
      - key: JIRA_API_TOKEN
        sync: false  # You'll need to set this manually in Render dashboard
      - key: JIRA_ORG_ID
        value: 493f453b-ec0f-4f77-a4e9-794b4efd41dd
      - key: JIRA_PROJECT_KEY
        value: CM3
      - key: JIRA_BOARD_ID
        value: "1"
      - key: JIRA_STORY_TYPE
        value: Story
      - key: JIRA_EPIC_TYPE
        value: Epic
      - key: JIRA_TASK_TYPE
        value: Task
      - key: JIRA_BASE_URL
        value: https://justinmbroxton.atlassian.net
      - key: JIRA_ISSUE_TYPE
        value: Story
      - key: JIRA_WEBHOOK_TOKEN
        generateValue: true
      - key: JIRA_EPIC_ISSUE_TYPE
        value: Epic
    region: oregon
    plan: starter

  # MCP Server
  - type: web
    name: speqq-mcp
    runtime: node
    repo: https://github.com/jbroxton/prototpe
    buildCommand: npm install
    startCommand: node scripts/start-mcp.mjs
    envVars:
      - key: MCP_PORT
        value: "10000"  # Render uses port 10000 by default
      - key: MCP_API_KEY
        generateValue: true  # Render will generate a secure random value
      - key: NEXT_PUBLIC_APP_BASE_URL
        value: https://speqq-app.onrender.com
    region: oregon
    plan: starter